from tags       import *
from columns    import *
from stacks     import *
from stack      import *
from window     import *

THREE_COLUMN_TAGS = Tags(
    cur=0,
    items=[
        Columns(
            cur=0,
            items=[
                Stacks(
                    cur=0,
                    items=[
                        Stack(
                            cur=0,
                            items=[
                                Window(),
                                Window(),
                            ]
                        ),
                        Stack(
                            cur=0,
                            items=[
                                Window(),
                            ]
                        ),
                    ]
                ),
                Stacks(
                    cur=0,
                    items=[
                        Stack(
                            cur=0,
                            items=[
                                Window(),
                            ]
                        ),
                    ]
                ),
                Stacks(
                    cur=0,
                    items=[
                        Stack(
                            cur=0,
                            items=[
                                Window(),
                            ]
                        ),
                        Stack(
                            cur=0,
                            items=[
                                Window(),
                            ]
                        ),
                        Stack(
                            cur=0,
                            items=[
                                Window(),
                            ]
                        ),
                    ]
                ),
            ]
        )
    ]
)

SIMPLE_TAGS = Tags(
    cur=0,
    items=[
        Columns(
            cur=0,
            items=[
                Stacks(
                    cur=0,
                    items=[
                        Stack(
                            cur=0,
                            items=[
                                Window(),
                            ]
                        ),
                    ]
                ),
                Stacks(
                    cur=0,
                    items=[
                        Stack(
                            cur=0,
                            items=[
                                Window(),
                            ]
                        ),
                    ]
                ),
            ]
        )
    ]
)
